swagger: "2.0"
info:
  title: API ChatBot
  description: "Ask ChatBot."
  version: "10.0.0"

schemes:
  - "https"

security:
  - api_key: []
securityDefinitions:
  api_key:
    name: api_key
    type: apiKey
    in: query

paths:
  "/ask":
    post:
      x-google-backend:
        address: https://asia-east1-fyp-open-data-hackathon.cloudfunctions.net/gcloudfunc-chatbot
      description: "Get map by asking ChatBot."
      operationId: "ask"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
              data:
                type: object
                properties:
                  chat:
                    type: string
                  kind:
                    type: string
                  coordinates:
                    type: array
                    items:
                      type: number
                      
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
                
  "/ask-map":
    post:
      x-google-backend:
        address: https://asia-east1-fyp-open-data-hackathon.cloudfunctions.net/gcloudfunc-chatbot-map	
      description: "Get answer by asking ChatBot Map."
      operationId: "ask-map"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
              data:
                type: object
                properties:
                  chat:
                    type: string
                  kind:
                    type: string
                  coordinates:
                    type: array
                    items:
                      type: number

      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
          
  "/ask-image":
    post:
      x-google-backend:
        address: https://asia-east1-fyp-open-data-hackathon.cloudfunctions.net/gcloudfunc-chatbot-image	
      description: "Get answer by asking ChatBot Map."
      operationId: "ask-image"
      parameters:
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              user_id:
                type: string
              data:
                type: object
                properties:
                  chat:
                    type: string
                  kind:
                    type: string
                  coordinates:
                    type: array
                    items:
                      type: number

      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
        "500":
          description: Internal Server Error
